# Environment Demo

name: Environment Demo
run-name: Environment Demo
on: workflow_dispatch
env:
  city_name: ${{ secrets.city }}
  
jobs:
  github-context:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: |
          echo city is "${{ env.city_name }}"
          echo "${{ env.city_name }}" | sed 's/\(.\)/\1 /g'
          echo done
