name: Hello World
run-name: Hello World Instance

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - main
  
jobs:
  HelloWorldJob:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Step
      run: echo -n ${{ toJSON(github) }}
    
