name: Job and Steps Context
run-name: Job and Steps Context
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "This is step 1"
    - name: step2
      run: echo job context is ${{toJSON(job)}}
      

  job2:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [job1]
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: echo job context is ${{toJSON(job)}}
    - name: step3
      run: echo steps context is ${{toJSON(steps)}}
      
  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
    - name: step1
      run: echo "This is step 1"
