name: Multiple Reusable Jobs
run-name: Multiple Reusable Jobs
on: workflow_dispatch

jobs:
  greeter-job:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/basic-reusable-job1.yml@main
    
  advanced-job:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/basic-reusable-job2.yml@main
    needs: greeter-job
    with:
      dept: HR
    secrets:
      city: hyderabad
  ormal-job:
    runs-on: ubuntu-latest
    needs: advanced-job
    steps:
      - run: echo output is ${{ needs.advanced-job.outputs.output-top-1 }} 
