# Scenario: 3 jobs are dependenct on each other sequentially and job2 has continue-on-error=true
# Finding: When job 2 fails, then job 3 still runs and teh workflow itself is marked as sucecssful
name: Needs Job Continue On Error Demo
run-name: Needs Job Continue On Error Demo
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "This is step 1"

  job2:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [job1]
    steps:
    - name: step2
      run: invalid-command
      
  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
    - name: step1
      run: echo "This is step 1"
