name: Needs Demo
run-name: Needs Demo
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "This is step 1"

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - name: step1
      run: echo "This is step 1"
      
  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
    - name: step1
      run: echo "This is step 1"
