# Scenario: 3 jobs are dependenct on each otehr sequentially
# Finding: When job 2 fails, then job 3 is skipepd and teh workflow itself is marked as failure
name: Needs Failure Demo
run-name: Needs Failure Demo
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "This is step 1"

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - name: step2
      run: invalid-command
      
  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
    - name: step1
      run: echo "This is step 1"
