name: Octokit REST api
run-name: Octokit REST api

on: workflow_dispatch

jobs:
  get-workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Hit REST api
      uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.city2 }}
          script: |
            response = await octokit.request('GET /repos/{owner}/{repo}/actions/workflows', {
                                    owner: 'allthings-dev',
                                    repo: 'github-actions-reusable-workflows',
                                    headers: {
                                      'X-GitHub-Api-Version': '2022-11-28'
                                    }
                                  })
            console.log("response: " , response);

