# Secrets Demo

name: Secrets Demo
run-name: Secrets Demo
on: workflow_dispatch
env:
  city_name: ${{ secrets.city }}
  
jobs:
  secret-handler:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo city is "${{ env.city_name }}"
          echo "${{ env.city_name }}" | sed 's/\(.\)/\1 /g'
          
