# Scenario: Here 3 jobs are in parallel.  In Job 2, the 2nd step fails on 2nd attempt. 
# Finding: Since jobs are in paralle, job 3 runs successfully even when job 2 fails on 2nd attempt. 
#          When step 2 of job 2 fails, step 3 is skipped and the job itself is marked as failure.
#          When job 2 fails, workflow is marked as failure
name: Step Continue On Error
run-name: Step Continue On Error
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "This is step 1"
    - name: step2
      continue-on-error: true
      run:  invalid-command
    - name: step3
      run: echo "This is step 3"
