# Scenario: Here job has 3 setps and step 2 will always fail and has continue on error = true
# Finding: Step 3 always runs and job is marked as successful
name: Step Continue On Error
run-name: Step Continue On Error
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "This is step 1"
    - name: step2
      continue-on-error: true
      run:  invalid-command
    - name: step3
      run: echo "This is step 3"
