name: Call a reusable workflows

on:
  push:
    paths:
      - '.github/workflows/test2.yml'

jobs:
  reuse1:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-1.yml@main
    with:
      donotfail: false
  reuse2:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-2.yml@main
    needs: [reuse1]
    if: always()
    with:
      someinput: ${{ toJSON(needs.reuse1.result) }}
